import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import NextAuthSessionProvider from "@/components/providers/SessionProvider";
import { getServerSession } from 'next-auth/next';
import { authOptions } from './api/auth/[...nextauth]/route';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CollabNest",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider session={session}>
        <NavbarWrapper />
        {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
